
steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['buid', '-t', 'gcr.io/tron-302502/kfp/custom:v1', '.']

    - name: python
      entrypoint: pip
      args: ["install", "-r", "requirements.txt", "--user"]
    
    - name: 'python'
      entrypoint: 'python'
      args: ['pipeline.py']
      id: 'compile'
    
    - name: 'gcr.io/cloud-builders/gsutil'
      args: ['cp', 'basic_pipeline_1.json', 'gs://tron-302502-bucket/aut']
      id: 'upload'
      waitFor: ['compile']
