steps:
    - name: python
      entrypoint: pip
      args: ["install", "-r", "test1/requirements.txt", "--user"]
    
    - name: 'python'
      entrypoint: 'python'
      args: ['test1/pipeline.py']
      id: 'compile'
    
    - name: 'gcr.io/cloud-builders/gsutil'
      args: ['cp', 'test1/basic_pipeline_1.json', 'gs://tron-302502-bucket/aut']
      id: 'upload'
      waitFor: ['compile']
